### PR TITLE
ring.Lifecycler: Ingester stuck in LEAVING state when ring tokens are increased.

### PR DESCRIPTION
**Pull request by sarthaktyagi-505**
What this PR does:
When starting a ring.Lifecycler, handle when previous ingester state is found in ring, its state is leaving and the number of tokens has changed. Tests are included.

What Changed?
1. Old code was only check if number of tokens before and number of tokens after ingester is in LEAVING state is equal to allow it to transition to ACTIVE state. This PR works on the similar logic used by @DylanGuedes to add or remove tokens if there is a increase or decrease tokens.
2. Also in the tests we weren't testing against number of tokens in the token file in the Dylan's PR, I have added a logic to add tokens in the temp file which is created to test the logic and test it against the tokens from the file.
3. Updated the runutil.go file to update the deprecated io.ioutil package.

The PR is based on the work done in this PR https://github.com/grafana/dskit/pull/79.  

Which issue(s) this PR fixes:

Fixes https://github.com/grafana/dskit/issues/73

Checklist

Tests updated
CHANGELOG.md updated - the order of entries should be [CHANGE], [FEATURE], [ENHANCEMENT], [BUGFIX]

### CODE REVIEW

**Comment by aknuds1** [comment]
Hey, sorry it took me so long to get to this. I've started reviewing your PR.

**Comment by sarthaktyagi-505** [comment]
@aknuds1 no worries, You can let me know how it goes.

-Sar

**Comment by aknuds1** [comment]
Could you have a look at my corresponding [PR](https://github.com/grafana/dskit/pull/79) again? I've revised it heavily, and I think it does the right thing now.

**Comment by 56quarters** [comment]
Closing since this was finished up in #79 . Thank you!

**Pull request closed without merging**
