### PR TITLE
Upgrade golang to 1.18

### PR DESCRIPTION
**Pull request by periklis**
**What this PR does**:
Upgrade golang to 1.18

**Which issue(s) this PR fixes**:

Required to support #185

**Checklist**
- [ ] Tests updated
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by cyriltovena — APPROVED** [review]
There might be other place where we need to update the go version like in the Dockerfile no ?

Otherwise LGTM

**Comment by periklis** [comment]
> There might be other place where we need to update the go version like in the Dockerfile no ?
> 
> Otherwise LGTM

There is no Dockerfile in this repo AFAICS.

**Comment by zalegrala** [comment]
https://github.com/periklis/dskit/pull/1 for the signature update if needd.

**Review by pracucci — APPROVED** [review]
👍 Unblocking

**Pull request merged**
