### PR TITLE
Fix typo in services README.md

### PR DESCRIPTION
**Pull request by hi-rustin**
**What this PR does**:
Fix typo in services README.md

### CODE REVIEW

**Comment by hi-rustin** [comment]
I guess the CI falling does not relate to my changes.

**Review by aknuds1 — APPROVED** [review]
LGTM, thanks!

**Comment by aknuds1** [comment]
> I guess the CI falling does not relate to my changes.

Hm.. yeah, looks like a mismatch between the build image and go.mod.

**Comment by aknuds1** [comment]
@hi-rustin please rebase against the dskit main branch, that probably will fix your CI error.

**Pull request merged**
